### ISSUE TITLE
Documentação dos perfis de usuários, suas necessidades e personas

### ISSUE THREAD

**Issue by adnamamonteiro** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2022-2-e4-proj-infra-t1-troca-comigo#2]

**Comment by LarysseGurgel** [comment]
H26a-ADS-CST - Compreender os usuários e definir uma proposta de solução: definir o problema de forma clara e objetiva, apresentando os objetivos, a justificativa e a motivação da escolha.
